server:
    port: 2323
    host_key_path: "host_key"
    max_users: 100

database:
    path: "bbs.db"

bbs:
    system_name: "Coastline BBS"
    sysop_name: "Sysop"
    welcome_message: |
        Welcome to Coastline BBS!

        A classic bulletin board system experience over SSH.
        Connect with other users, read messages, and explore!
    max_line_length: 79
    colors:
        primary: "cyan"
        secondary: "red"
        accent: "yellow"
        text: "white"
        background: "black"
        border: "blue"
        success: "green"
        error: "red"
        highlight: "bright_white"
    menus:
        - id: "main"
          title: "Main Menu"
          description: "Main BBS Menu"
          command: "main_menu"
          access_level: 0
          submenu:
              - id: "bulletins"
                title: "Bulletins"
                description: "Read system bulletins"
                command: "bulletins"
                access_level: 0
                hotkey: "b"
              - id: "messages"
                title: "Messages"
                description: "Message areas"
                command: "messages"
                access_level: 0
                hotkey: "m"
              - id: "files"
                title: "Files"
                description: "File areas"
                command: "files"
                access_level: 0
                hotkey: "f"
              - id: "games"
                title: "Games"
                description: "Online games"
                command: "games"
                access_level: 0
                hotkey: "g"
              - id: "users"
                title: "Users"
                description: "User listings"
                command: "users"
                access_level: 0
                hotkey: "u"
              - id: "sysop"
                title: "Sysop"
                description: "System operator menu"
                command: "sysop_menu"
                access_level: 255
                hotkey: "s"
              - id: "goodbye"
                title: "Goodbye"
                description: "Logoff system"
                command: "goodbye"
                access_level: 0
                hotkey: "q"

        - id: "sysop_menu"
          title: "System Operator Menu"
          description: "Sysop Management Menu"
          command: "sysop_menu"
          access_level: 255
          submenu:
              - id: "create_user"
                title: "Create New User"
                description: "Create New User Account"
                command: "create_user"
                access_level: 255
                hotkey: "c"
              - id: "edit_user"
                title: "Edit User Account"
                description: "Edit User Account"
                command: "edit_user"
                access_level: 255
                hotkey: "e"
              - id: "delete_user"
                title: "Delete User Account"
                description: "Delete User Account"
                command: "delete_user"
                access_level: 255
                hotkey: "d"
              - id: "view_users"
                title: "View All Users"
                description: "View All Users"
                command: "view_users"
                access_level: 255
                hotkey: "v"
              - id: "change_password"
                title: "Change User Password"
                description: "Change User Password"
                command: "change_password"
                access_level: 255
                hotkey: "p"
              - id: "toggle_user"
                title: "Toggle User Status"
                description: "Toggle User Active Status"
                command: "toggle_user"
                access_level: 255
                hotkey: "t"
              - id: "system_stats"
                title: "System Statistics"
                description: "System Statistics"
                command: "system_stats"
                access_level: 255
                hotkey: "s"
              - id: "bulletin_management"
                title: "Bulletin Management"
                description: "Bulletin Management"
                command: "bulletin_management"
                access_level: 255
                hotkey: "b"
