server:
    port: 2323
    host_key_path: "host_key"
    max_users: 100

database:
    path: "bbs.db"

bbs:
    system_name: "Coastline BBS"
    sysop_name: "Sysop"
    welcome_message: |
        Welcome to Coastline BBS!

        A classic bulletin board system experience over SSH.
        Connect with other users, read messages, and explore!
    max_line_length: 79
    colors:
        primary: "cyan"
        secondary: "red"
        accent: "yellow"
        text: "white"
        background: "black"
        border: "blue"
        success: "green"
        error: "red"
        highlight: "bright_white"
    menus:
        - id: "main"
          title: "Main Menu"
          description: "Main BBS Menu"
          command: "main_menu"
          access_level: 0
          submenu:
              - id: "bulletins"
                title: "Bulletins"
                description: "Read system bulletins"
                command: "bulletins"
                access_level: 0
                hotkey: "b"
              - id: "messages"
                title: "Messages"
                description: "Message areas"
                command: "messages"
                access_level: 0
                hotkey: "m"
              - id: "files"
                title: "Files"
                description: "File areas"
                command: "files"
                access_level: 0
                hotkey: "f"
              - id: "games"
                title: "Games"
                description: "Online games"
                command: "games"
                access_level: 0
                hotkey: "g"
              - id: "users"
                title: "Users"
                description: "User listings"
                command: "users"
                access_level: 0
                hotkey: "u"
              - id: "sysop"
                title: "Sysop"
                description: "System operator menu"
                command: "sysop_menu"
                access_level: 255
                hotkey: "s"
              - id: "goodbye"
                title: "Goodbye"
                description: "Logoff system"
                command: "goodbye"
                access_level: 0
                hotkey: "q"

        - id: "sysop_menu"
          title: "System Operator Menu"
          description: "Sysop Management Menu"
          command: "sysop_menu"
          access_level: 255
          submenu:
              - id: "user_management"
                title: "User Management"
                description: "Manage user accounts"
                command: "sysop_user_menu"
                access_level: 255
                hotkey: "u"
              - id: "bulletin_management"
                title: "Bulletin Management"
                description: "Manage system bulletins"
                command: "sysop_bulletin_menu"
                access_level: 255
                hotkey: "b"
              - id: "system_stats"
                title: "System Statistics"
                description: "View system statistics"
                command: "sysop_stats"
                access_level: 255
                hotkey: "s"
              - id: "system_config"
                title: "System Configuration"
                description: "Configure system settings"
                command: "sysop_config"
                access_level: 255
                hotkey: "c"
              - id: "database_maintenance"
                title: "Database Maintenance"
                description: "Database maintenance tools"
                command: "sysop_maintenance"
                access_level: 255
                hotkey: "d"

        - id: "sysop_user_menu"
          title: "Sysop User Editor"
          description: "User Management Menu"
          command: "sysop_user_menu"
          access_level: 255
          submenu:
              - id: "list_users"
                title: "List Users"
                description: "List all users"
                command: "sysop_user_list"
                access_level: 255
                hotkey: "l"
              - id: "create_user"
                title: "Create User"
                description: "Create new user"
                command: "sysop_user_create"
                access_level: 255
                hotkey: "c"
              - id: "edit_user"
                title: "Edit User"
                description: "Edit existing user"
                command: "sysop_user_edit"
                access_level: 255
                hotkey: "e"
              - id: "delete_user"
                title: "Delete User"
                description: "Delete user"
                command: "sysop_user_delete"
                access_level: 255
                hotkey: "d"
              - id: "change_password"
                title: "Change Password"
                description: "Change user password"
                command: "sysop_user_password"
                access_level: 255
                hotkey: "p"
              - id: "toggle_status"
                title: "Toggle Status"
                description: "Toggle user active status"
                command: "sysop_user_toggle"
                access_level: 255
                hotkey: "t"

        - id: "sysop_bulletin_menu"
          title: "Sysop Bulletin Editor"
          description: "Bulletin Management Menu"
          command: "sysop_bulletin_menu"
          access_level: 255
          submenu:
              - id: "list_bulletins"
                title: "List Bulletins"
                description: "List all bulletins"
                command: "sysop_bulletin_list"
                access_level: 255
                hotkey: "l"
              - id: "create_bulletin"
                title: "Create Bulletin"
                description: "Create new bulletin"
                command: "sysop_bulletin_create"
                access_level: 255
                hotkey: "c"
              - id: "edit_bulletin"
                title: "Edit Bulletin"
                description: "Edit existing bulletin"
                command: "sysop_bulletin_edit"
                access_level: 255
                hotkey: "e"
              - id: "delete_bulletin"
                title: "Delete Bulletin"
                description: "Delete bulletin"
                command: "sysop_bulletin_delete"
                access_level: 255
                hotkey: "d"

sysop:
    title: "System Administration"
    instructions: "Navigate: ↑↓  Select: Enter  Quit: Q"
    options:
        - id: "create_user"
          title: "Create New User"
          description: "1) Create New User Account"
          command: "create_user"
        - id: "edit_user"
          title: "Edit User Account"
          description: "2) Edit User Account"
          command: "edit_user"
        - id: "delete_user"
          title: "Delete User Account"
          description: "3) Delete User Account"
          command: "delete_user"
        - id: "view_users"
          title: "View All Users"
          description: "4) View All Users"
          command: "view_users"
        - id: "change_password"
          title: "Change User Password"
          description: "5) Change User Password"
          command: "change_password"
        - id: "toggle_user"
          title: "Toggle User Status"
          description: "6) Toggle User Active Status"
          command: "toggle_user"
        - id: "system_stats"
          title: "System Statistics"
          description: "7) System Statistics"
          command: "system_stats"
        - id: "bulletin_management"
          title: "Bulletin Management"
          description: "8) Bulletin Management"
          command: "bulletin_management"
